test: test.o linkedList.o Hash.o Nary.o Bst.o
	gcc -o FinalBin linkedList.o Hash.o Nary.o Bst.o

test.o: test.c
	gcc -c test.c

linkedList.o: LinkedList.c
	gcc -c LinkedList.c

Hash.o: Hash.c
	gcc -c Hash.c

Nary.o: Nary.c
	gcc -c Nary.c

Bst.o: Bst.c
	gcc -c Bst.c
