#ifndef ERRCODES_H_INCLUDED
#define ERRCODES_H_INCLUDED

/*
 * VFS Error codes
 * Last updated: 15-Nov-2012
 */
//New  (if the argument is not specified)
#define ERR_VFS_CREATE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_CREATE_01 "DATA_FILE_ALREADY_EXISTS\n"
#define ERR_VFS_CREATE_02 "CANNOT_CREATE_DATAFILE\n"

 // The slash (/) character is not allowed
#define ERR_VFS_CREATE_03 "INVALID_CHARACTER_IN_NAME\n"
// Valid range for size is 1 to 1024 (inclusive)
#define ERR_VFS_CREATE_04 "INVALID_SIZE\n"
//New   (If label name exceeds 30 characters)
#define ERR_VFS_CREATE_05 "VFS_LABEL_TOO_LARGE\n"

#define ERR_VFS_MOUNT_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_MOUNT_01 "DATA_FILE_NOT_FOUND\n"
#define ERR_VFS_MOUNT_02 "CANNOT_READ_FROM_FILE\n"
//New
#define ERR_VFS_MOUNT_03 "VFS_ALREADY_MOUNTED\n"

#define ERR_VFS_UNMOUNT_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
// Use when fopen fails
#define ERR_VFS_UNMOUNT_01 "DATA_FILE_NOT_FOUND\n"
// Use when fwrite fails
#define ERR_VFS_UNMOUNT_02 "CANNOT_WRITE_TO_FILE\n"
//New
#define ERR_VFS_UNMOUNT_03 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_MAKEDIR_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
//changed to FILESYSTEM_FULL from UNABLE_TO_CREATE_NEWDIR
#define ERR_VFS_MAKEDIR_01 "FILESYSTEM_FULL\n"
#define ERR_VFS_MAKEDIR_02 "INVALID_CHARACTER_IN_DIRNAME\n"
#define ERR_VFS_MAKEDIR_03 "DIRECTORY_ALREADY_EXISTS\n"
//New
#define ERR_VFS_MAKEDIR_05 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_DELETEDIR_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_DELETEDIR_01 "CANNOT_FIND_SPECIFIED_DIR\n"
#define ERR_VFS_DELETEDIR_02 "DIRECTORY_IS_NOT_EMPTY\n"
//New
#define ERR_VFS_DELETEDIR_04 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_MOVEDIR_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_MOVEDIR_01 "CANNOT_FIND_SPECIFIED_SOURCEDIR\n"
//(if specified dir is not there, it is not created in this case unlike in add dir)
#define ERR_VFS_MOVEDIR_02 "CANNOT_FIND_SPECIFIED_DESTINATIONDIR\n"
//New
#define ERR_VFS_MOVEDIR_04 "SOURCE_CANNOT_BE_FILE\n"
#define ERR_VFS_MOVEDIR_05 "DESTINATION_ALREADY_HAVE_SOURCE_DIR\n"
//New
#define ERR_VFS_MOVEDIR_06 "CANNOT_MOVE_PARENT_TO_CHILD_DIR\n"
//New
#define ERR_VFS_MOVEDIR_07 "DESTINATION_CANNOT_BE_FILE\n"
//New
#define ERR_VFS_MOVEDIR_08 "VFS_NOT_MOUNTED\n"

//New
#define ERR_VFS_LISTDIR_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_LISTDIR_01 "CANNOT_FIND_SPECIFIED_PATH_OR_DIR\n"
#define ERR_VFS_LISTDIR_02 "INVALID_FLAG\n"
#define ERR_VFS_LISTDIR_03 "VFS_NOT_MOUNTED\n"
#define ERR_VFS_LISTDIR_04 "CANNOT_CREATE_OUTPUTFILE\n"

#define ERR_VFS_ADDFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_ADDFILE_02 "INVALID_CHARACTER_IN_FILENAME\n"
#define ERR_VFS_ADDFILE_03 "FILE_ALREADY_EXISTS\n"
#define ERR_VFS_ADDFILE_04 "FILE_SYSTEM_FULL\n"
//New
#define ERR_VFS_ADDFILE_05 "CANNOT_WRITE_TO_DATAFILE\n"
//New : (if data exceeds block size)
#define ERR_VFS_ADDFILE_06 "FILE_TOO_LARGE\n"
//New
#define ERR_VFS_ADDFILE_07 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_LISTFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_LISTFILE_01 "SOURCE_FILE_PATH_NOT_FOUND\n"
#define ERR_VFS_LISTFILE_02 "NOT_A_TEXT_FILE\n"
//New
#define ERR_VFS_LISTFILE_03 "CANNOT_CREATE_OUTPUTFILE\n"
//New
#define ERR_VFS_LISTFILE_04 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_UPDATEFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_UPDATEFILE_01 "INTERNAL_FILE_NOT_FOUND\n"
#define ERR_VFS_UPDATEFILE_02 "EXTERNAL_FILE_NOT_FOUND\n"
//New
#define ERR_VFS_UPDATEFILE_03 "EXTERNAL_FILE_TOO_LARGE\n"
//New
#define ERR_VFS_UPDATEFILE_04 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_REMOVEFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
// Use this error even when the given argument is a directory and not a file
#define ERR_VFS_REMOVEFILE_01 "CANNOT_FIND_SPECIFIED_FILE\n"
//New
#define ERR_VFS_REMOVEFILE_02 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_MOVEFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_MOVEFILE_01 "CANNOT_FIND_SOURCEFILE\n"
#define ERR_VFS_MOVEFILE_02 "CANNOT_FIND_DESTINATION_PATH\n"
#define ERR_VFS_MOVEFILE_05 "DESTINATION_CANNOT_BE_FILE\n"
//New
#define ERR_VFS_MOVEFILE_06 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_COPYFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_COPYFILE_01 "CANNOT_FIND_SOURCEFILE\n"
#define ERR_VFS_COPYFILE_02 "CANNOT_FIND_DESTINATIONFILE\n"
#define ERR_VFS_COPYFILE_03 "CANNOT_COPY_DIR_TO_FILE\n"
#define ERR_VFS_COPYFILE_04 "FILE_SYSTEM_FULL\n"
#define ERR_VFS_COPYFILE_05 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_EXPORTFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
#define ERR_VFS_EXPORTFILE_01 "CANNOT_FIND_SOURCEFILE\n"
#define ERR_VFS_EXPORTFILE_02 "CANNOT_CREATE_OUTPUTFILE\n"
#define ERR_VFS_EXPORTFILE_03 "CANNOT_EXPORT_DIR\n"
//New
#define ERR_VFS_EXPORTFILE_04 "VFS_NOT_MOUNTED\n"

#define ERR_VFS_SEARCHFILE_00 "VFS_INSUFFICIENT_ARGUMENTS\n"
//New
#define ERR_VFS_SEARCHFILE_02 "VFS_NOT_MOUNTED\n"

#endif
